### ISSUE TITLE
Test on own data，and some problem on the turning movement!

### ISSUE THREAD

**Issue by mightyhao** [mbrossar/ai-imu-dr#62]
Hi, @mbrossar.,I'm interested in your great job!But I can't get good result on my own test data.
       I use IMU of the intel realsense T265 on the handcart to move on the straight line,and turn sometimes.The move speed is about 1m/s.I got the result as follows:
![Figure_1](https://user-images.githubusercontent.com/9162558/124845149-afc04a00-dfc8-11eb-9cef-a0f28b8f779f.png)
![Figure_3](https://user-images.githubusercontent.com/9162558/124845183-c1a1ed00-dfc8-11eb-99d6-abfc5a6cc7c2.png)
![Figure_2](https://user-images.githubusercontent.com/9162558/124845438-5278c880-dfc9-11eb-8c9d-9aa12504fc79.png)
![Figure_4](https://user-images.githubusercontent.com/9162558/124845414-47be3380-dfc9-11eb-80e1-46efb33ef64a.png)
![Figure_5](https://user-images.githubusercontent.com/9162558/124845423-4b51ba80-dfc9-11eb-9b8a-db75c2b5b0a7.png)
      I have tuned the initial parameters hardly, like initial error covariance, process noise covariance and measurement covariance. but still,the result is not good  on the turn position of the  trajectory, could you please give me some advice on how to solve this problem? Thank you!

**Comment by scott81321** [comment]
Hello I gather you got Brossard's program to work?  I tried his program on a KITTI dataset but the program wants a "reformatted pickle format" of the KITTI raw dataset - whatever that means (?)  Brossard's own datasets can no longer be download since his University closed his account after he  graduated.

**Comment by scott81321** [comment]
Hello @mightyhao  Did you check your data?  Did you make sure all timestamps were sort in forward time with no time gaps greater than 0.1 seconds?

**Comment by milkcoffee365** [comment]
Maybe the precision of the imu is not good enough. The data used in this paper is very accuracy, very small bias and noise. I have try run ai_imu with smart phone data, and the result is not good.  But, when use GPS's position update, the result comes much better.

**Comment by salkartrack** [comment]
@scott81321  @milkcoffee365 @marooncn Did you guys ever manage to train the model with your own dataset?
Also additionally, how did you gather ground truth data for your own dataset? Did you use oxts like KITTI?

**Comment by milkcoffee365** [comment]
I tried to run Ai-Imu without the model, use the paper's kitty data, this result seems no big different. So, I think the model is not necessary. The main contribution of this paper should be attributed to the IEKF modeling. 
I collect my own data with smartphones, and no ground truth. I regard GPS as ground truth about 1HZ, not same with this paper. Remove some continuous GPS to simulate the GPS outage.

**Comment by 1248280302** [comment]
@mightyhao @milkcoffee365 Hey guys.How do you test this code with only IMU data?I have seen the KITTI dataset include GPS data and other error conv.Could it work with IMU 6 axis basic data?

**Comment by ajay1606** [comment]
Hello @mightyhao @scott81321 are you able to test working for this repo code with your own data ! Would you please share some of your experience on that ! I also trying to convert my imu bag data into the KITTI format mentioned by @mbrossar.

Currently, I have tested the code with provided example KITTI dataset and it works well as shown in the README. Also tried testing the code with KITTI raw data (using only OXTS file format and enabling read_data=1 in the code main_kitti.py) and the results are very good.

Similarly to KITTI OXTS ( .txt) format, I have generated a .txt file and time stamp file to input to this algorithm after converting bag file data into OXTS format as below. But obtained results look very strange and couldn't understand clearly where I am missing !! Please, anyone, guide me to plug my bag values into this repository code. Really appreciate any response. 

Here is the Bag to OXTS conversion: 

**Original IMU data from bag file**
```
header: 
  seq: 4201
  stamp: 
    secs: 1633681151
    nsecs: 664900319
  frame_id: "imu_link"
orientation: 
  x: -0.0040089504111
  y: -0.0138810181661
  z: -0.132263991438
  w: 0.991109218109
orientation_covariance: [0.0009797271326400653, 0.0, 0.0, 0.0, 0.0012425838195850997, 0.0, 0.0, 0.0, 1.462497123398009]
angular_velocity: 
  x: 0.00138823367606
  y: 0.000741836739148
  z: 7.29580193999e-05
angular_velocity_covariance: [-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: 0.00724529630717
  y: -0.0154154589063
  z: 0.0730627986135
linear_acceleration_covariance: [-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
```
**From IMU Topic:**
IMU is installed in a way that XYZ coordinates matches with the vehicle FLU coordinate axis. 
```
  af=msg->linear_acceleration.x;
  ax=msg->linear_acceleration.x;
  al=msg->linear_acceleration.y;
  ay=msg->linear_acceleration.y;
  au=msg->linear_acceleration.z;
  az=msg->linear_acceleration.z; 

  wf=msg->angular_velocity.x;
  wx=msg->angular_velocity.x;
  wl=msg->angular_velocity.y;
  wy=msg->angular_velocity.y;
  wu=msg->angular_velocity.z;
  wz=msg->angular_velocity.z; 
```
**From Twist topic:**
Not Sure about vn, ve observations! How can i compute?
```
// Not sure about these values
  vn=msg->twist.linear.x;
  ve=msg->twist.linear.y;

  vf=msg->twist.linear.x;
  vl=msg->twist.linear.y;
  vu=msg->twist.linear.z; 
```

**From GNSS topic:**
```
  lat=fix->latitude; 
  lon=fix->longitude;
  alt=fix->altitude ;  
```

**Expected Trajectory (Original Trajectory)**
![image](https://user-images.githubusercontent.com/29722843/181454888-ef2dae8f-e24c-443a-91c0-dafe5b1bf3c9.png)

**Obtained Trajectory** 
![image](https://user-images.githubusercontent.com/29722843/181456245-9a89f08c-7e7f-4c00-90a0-9930e61f21e8.png)

**Position Graph:**
![image](https://user-images.githubusercontent.com/29722843/181456310-5df69e5d-a0c0-4ae0-950e-24996cc62b99.png)

**Orientation Graph:**
![image](https://user-images.githubusercontent.com/29722843/181456480-f1d20ed3-4319-41ad-8194-f8cfabb3c487.png)

Really any response much appreciated.
